#!/bin/bash
set -euo pipefail

# Load Common Library
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPT_DIR/common.sh"

# Global Config
VSFTPD_CONF="/etc/vsftpd.conf"
FTP_PASSWD_FILE="/etc/vsftpd/ftppasswd"
USER_CONFIG_DIR="/etc/vsftpd/user_conf"
if [[ "$HB_PLATFORM" == "rpi5" ]]; then
    BOOT_CONFIG="/boot/firmware/config.txt"
else
    BOOT_CONFIG=""
fi
WATCHDOG_CONF="/etc/watchdog.conf"
NC_CRON_FILE="/etc/cron.d/nextcloud-cron"

# --- Helper: Configure Watchdog (Pi 5 only) ---
configure_watchdog() {
    if [[ "$HB_PLATFORM" != "rpi5" ]]; then
        log_info "Watchdog configuration is Pi-specific. Skipping on ${HB_PLATFORM}."
        return 0
    fi

    local action="$1" # enable | disable

    if [[ "$action" == "enable" ]]; then
        log_info "Enabling System Watchdog..."
        
        # 1. Boot Config (Idempotent)
        if ! grep -q "^dtparam=watchdog=on" "$BOOT_CONFIG"; then
            # Ensure we don't append to a line without newline
            sed -i '$a dtparam=watchdog=on' "$BOOT_CONFIG"
            log_info "Added dtparam=watchdog=on to config.txt"
        fi

        # 2. Install Package
        if ! dpkg -s watchdog >/dev/null 2>&1; then
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -qq && apt-get install -y -qq watchdog
        fi

        # 3. Configure Service
        if [[ -f "$WATCHDOG_CONF" ]]; then
            sed -i 's/^#watchdog-device/watchdog-device/' "$WATCHDOG_CONF"
            sed -i 's/^#max-load-1/max-load-1/' "$WATCHDOG_CONF"
            # Ensure critical settings
            if ! grep -q "watchdog-timeout" "$WATCHDOG_CONF"; then
                echo "watchdog-timeout = 15" >> "$WATCHDOG_CONF"
            fi
        fi

        # 4. Enable Service
        systemctl enable --now watchdog
        log_info "Watchdog enabled and started."

    elif [[ "$action" == "disable" ]]; then
        log_info "Disabling System Watchdog..."
        systemctl disable --now watchdog
        # We generally leave the boot config alone to avoid reboot friction, 
        # but stopping the service is sufficient.
    fi
}

# --- Helper: Configure Nextcloud Cron ---
configure_nc_cron() {
    local nc_cid=$(get_nc_cid)
    if [[ -z "$nc_cid" ]]; then die "Nextcloud container not running."; fi

    log_info "Configuring Nextcloud system cron..."
    
    # 1. Set mode in Nextcloud
    docker exec -u www-data "$nc_cid" php occ background:cron || true

    # 2. Write System Cron file
    # Uses dynamic container ID lookup inside the cron command for robustness across restarts
    cat > "$NC_CRON_FILE" <<EOF
# Generated by HomeBrain Manager
*/5 * * * * root docker exec -u www-data \$(docker compose -f $COMPOSE_FILE ps -q nextcloud) php cron.php > /dev/null 2>&1
EOF
    chmod 644 "$NC_CRON_FILE"
    systemctl restart cron
    
    log_info "Nextcloud cron configured."
}

# --- Helper: Configure PCIe Speed (Pi 5 only) ---
configure_pci_speed() {
    if [[ "$HB_PLATFORM" != "rpi5" ]]; then
        log_info "PCIe configuration is Pi-specific. Skipping on ${HB_PLATFORM}."
        return 0
    fi

    local speed="$1" # gen2 | gen3

    if [[ "$speed" == "gen3" ]]; then
        log_info "Enabling PCIe Gen 3.0 speeds..."
        if ! grep -q "^dtparam=pciex1_gen=3" "$BOOT_CONFIG"; then
             sed -i '$a dtparam=pciex1_gen=3' "$BOOT_CONFIG"
             log_info "Gen 3 enabled. Reboot required."
        fi
    else
        log_info "Reverting to PCIe Gen 2.0 (Default)..."
        sed -i '/^dtparam=pciex1_gen=3/d' "$BOOT_CONFIG"
    fi
}

# --- Status Checks (JSON Output) ---
get_system_config_status() {
    load_env

    # Watchdog & PCIe (Pi-only)
    local wd_status="unsupported"
    local pci_status="unsupported"
    if [[ "$HB_PLATFORM" == "rpi5" ]]; then
        wd_status="disabled"
        if systemctl is-active --quiet watchdog; then wd_status="enabled"; fi
        pci_status="gen2"
        if [[ -n "$BOOT_CONFIG" ]] && grep -q "^dtparam=pciex1_gen=3" "$BOOT_CONFIG" 2>/dev/null; then pci_status="gen3"; fi
    fi

    # NC Cron
    local cron_status="unknown"
    local nc_cid=$(get_nc_cid)
    if [[ -n "$nc_cid" ]]; then
        cron_status=$(docker exec -u www-data "$nc_cid" php occ config:app:get core backgroundjobs_mode 2>/dev/null || echo "unknown")
    fi

    # llama-server (inference engine) — platform-aware binary path
    local llama_status="not_installed"
    local llama_bin
    llama_bin=$(get_llama_bin_path)
    if [[ -f "$llama_bin" ]]; then
        if systemctl is-active --quiet llama-server 2>/dev/null; then
            if curl -sf --max-time 3 http://127.0.0.1:8001/health >/dev/null 2>&1; then
                llama_status="running"
            else
                llama_status="starting"
            fi
        else
            llama_status="disabled"
        fi
    fi

    # OpenClaw AI (system service managed by openclaw daemon)
    local ai_status="not_installed"
    if command -v openclaw >/dev/null 2>&1; then
        local oc_output
        oc_output=$(run_as_admin timeout 15 openclaw gateway status 2>/dev/null || true)
        if echo "$oc_output" | grep -qi "running\|active\|online"; then
            ai_status="running"
        else
            ai_status="disabled"
        fi
    fi

    # WhatsApp channel link status
    local wa_status="disabled"
    if command -v openclaw >/dev/null 2>&1 && [[ "$ai_status" != "not_installed" ]]; then
        local wa_output
        wa_output=$(run_as_admin timeout 10 openclaw channels status --probe 2>/dev/null || true)
        if echo "$wa_output" | grep -qi "whatsapp.*not linked\|whatsapp.*disconnected\|whatsapp.*logged out"; then
            wa_status="not_linked"
        elif echo "$wa_output" | grep -qi "whatsapp.*linked\|whatsapp.*connected"; then
            wa_status="linked"
        fi
    fi

    # whisper-server + proxy (speech-to-text)
    local whisper_status="not_installed"
    if [[ -x "/home/admin/whisper-server/whisper-server" ]]; then
        if systemctl is-active --quiet whisper-server 2>/dev/null \
           && systemctl is-active --quiet whisper-proxy 2>/dev/null; then
            whisper_status="running"
        else
            whisper_status="stopped"
        fi
    fi

    local current_model="${AI_MODEL_ID:-}"
    echo "{\"watchdog\": \"$wd_status\", \"pci\": \"$pci_status\", \"cron\": \"$cron_status\", \"llama_server\": \"$llama_status\", \"openclaw\": \"$ai_status\", \"whatsapp\": \"$wa_status\", \"whisper\": \"$whisper_status\", \"platform\": \"$HB_PLATFORM\", \"ai_model_id\": \"$current_model\"}"
}

# --- Helper: Install Dependencies ---
ensure_ftp_dependencies() {
    if ! command -v vsftpd >/dev/null 2>&1; then
        # Offline check: Cannot install if offline
        if ! check_internet; then
             die "VSFTPD not found and no internet connection. Cannot install FTP dependencies."
        fi
        
        log_info "Installing VSFTPD and utilities..."
        export DEBIAN_FRONTEND=noninteractive
        
        # Resilience: Wait for lock
        wait_for_apt_lock

        apt-get update -qq
        apt-get install -y -qq vsftpd libpam-pwdfile apache2-utils inotify-tools
    fi
}

# --- Helper: Configure VSFTPD ---
configure_vsftpd() {
    load_env
    
    # Backup original if not done
    if [ ! -f "${VSFTPD_CONF}.bak" ]; then
        cp "$VSFTPD_CONF" "${VSFTPD_CONF}.bak"
    fi

    # Fix www-data home for chroot compatibility (Idempotent)
    local www_home
    www_home=$(getent passwd www-data | cut -d: -f6)
    if [ "$www_home" != "$NEXTCLOUD_DATA_DIR" ]; then
        log_info "Updating www-data home directory to $NEXTCLOUD_DATA_DIR..."
        usermod -d "$NEXTCLOUD_DATA_DIR" www-data
    fi

    # Write Config (Hardened)
    cat > "$VSFTPD_CONF" <<EOF
listen=YES
listen_ipv6=NO
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES
guest_enable=YES
guest_username=www-data
virtual_use_local_privs=YES
user_sub_token=\$USER
local_root=${NEXTCLOUD_DATA_DIR}/\$USER/files/uploads
user_config_dir=${USER_CONFIG_DIR}
pam_service_name=vsftpd.virtual
pasv_min_port=40000
pasv_max_port=50000
EOF

    # Configure PAM
    if ! grep -q "pam_pwdfile.so" /etc/pam.d/vsftpd.virtual 2>/dev/null; then
        cat > /etc/pam.d/vsftpd.virtual <<EOF
auth    required pam_pwdfile.so pwdfile ${FTP_PASSWD_FILE}
account required pam_permit.so
EOF
    fi

    mkdir -p "$USER_CONFIG_DIR"
}

# --- Action: Setup FTP User ---
setup_ftp_user() {
    local nc_user="$1"
    local ftp_user="$2"
    local ftp_pass="$3"

    load_env
    ensure_ftp_dependencies
    configure_vsftpd

    # 1. Verify Nextcloud User
    local nc_cid=$(get_nc_cid)
    if [[ -z "$nc_cid" ]]; then die "Nextcloud container is not running."; fi
    
    if ! docker exec -u www-data "$nc_cid" php occ user:info "$nc_user" >/dev/null 2>&1; then
        die "Nextcloud user '$nc_user' does not exist."
    fi

    # 2. Create Upload Directory
    local upload_dir="${NEXTCLOUD_DATA_DIR}/${nc_user}/files/uploads"
    if [ ! -d "$upload_dir" ]; then
        log_info "Creating upload directory: $upload_dir"
        mkdir -p "$upload_dir"
        chown -R www-data:www-data "$upload_dir"
    fi

    # 3. Add/Update Virtual FTP User
    # Use -B to verify bcrypt compatibility if needed, but md5 (-d) is standard for pam_pwdfile
    if [ ! -f "$FTP_PASSWD_FILE" ]; then
        htpasswd -b -c -d "$FTP_PASSWD_FILE" "$ftp_user" "$ftp_pass"
    else
        htpasswd -b -d "$FTP_PASSWD_FILE" "$ftp_user" "$ftp_pass"
    fi

    # 4. Map FTP User to NC User Directory
    # We store the NC user in a comment for the API to read back later
    echo "# NC_USER=${nc_user}" > "${USER_CONFIG_DIR}/${ftp_user}"
    echo "local_root=${NEXTCLOUD_DATA_DIR}/${nc_user}/files/uploads" >> "${USER_CONFIG_DIR}/${ftp_user}"

    # 5. Setup Watcher Service (inotify)
    local service_name="nextcloud-ftp-sync@${nc_user}"
    local watcher_script="/usr/local/bin/nextcloud-ftp-sync.sh"
    
    # Create robust watcher script
    cat > "$watcher_script" <<EOF
#!/bin/bash
NC_USER="\$1"
WATCH_DIR="${NEXTCLOUD_DATA_DIR}/\$NC_USER/files/uploads"
# Wait for Docker
until docker info >/dev/null 2>&1; do sleep 5; done

while true; do
  # Wait for file events
  inotifywait -e close_write,moved_to,create -r "\$WATCH_DIR"
  
  # Trigger Scan (debounce slightly)
  sleep 2
  NC_CID=\$(docker compose -f "${COMPOSE_FILE}" ps -q nextcloud 2>/dev/null)
  if [[ -n "\$NC_CID" ]]; then
      echo "Scanning files for \$NC_USER..."
      docker exec -u www-data "\$NC_CID" php occ files:scan --path="/\$NC_USER/files/uploads"
  fi
done
EOF
    chmod +x "$watcher_script"

    # Create/Enable Systemd Service template
    if [ ! -f /etc/systemd/system/nextcloud-ftp-sync@.service ]; then
        cat > /etc/systemd/system/nextcloud-ftp-sync@.service <<EOF
[Unit]
Description=Nextcloud FTP Sync Watcher for %i
After=docker.service

[Service]
ExecStart=$watcher_script %i
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload
    fi

    systemctl enable --now "$service_name"
    systemctl restart vsftpd
    
    log_info "FTP User '$ftp_user' mapped to Nextcloud user '$nc_user' successfully."
}

# --- Action: Delete FTP User ---
delete_ftp_user() {
    local ftp_user="$1"
    
    if [ -f "$FTP_PASSWD_FILE" ]; then
        htpasswd -D "$FTP_PASSWD_FILE" "$ftp_user"
    fi
    
    if [ -f "${USER_CONFIG_DIR}/${ftp_user}" ]; then
        rm "${USER_CONFIG_DIR}/${ftp_user}"
    fi
    
    # Note: We do NOT stop the sync service because multiple FTP users might map to the same NC user.
    # Service cleanup is left manual or handled by a deeper logic if needed.
    
    systemctl restart vsftpd
    log_info "FTP User '$ftp_user' deleted."
}

# --- Action: Activate Tunnels (Post-Setup) ---
activate_tunnels() {
    log_info "Initializing Tunnel Activation..."
    load_env
    
    local profiles=$(get_tunnel_profiles)
    
    if [[ -z "$profiles" ]]; then
        log_info "No tunnel profiles configured (Local Mode). Skipping activation."
    else
        log_info "Activating tunnel profiles: $profiles"
        docker compose --env-file "$ENV_FILE" $(get_compose_args) $profiles up -d --remove-orphans
        log_info "Tunnel services started."
    fi
}

create_ha_admin() {
    local HA_PASSWORD="$1"
    if [ -z "$HA_PASSWORD" ]; then
        die "HA_PASSWORD not provided to utility."
    fi

    # Use the built-in health check helper first
    # This ensures the container is actually running before we spam the API
    wait_for_healthy "homeassistant" 120 || { log_error "HA container not healthy"; return 1; }

    log_info "Creating Home Assistant Admin Account..."
    local HA_URL="http://127.0.0.1:8123"
    local CLIENT_ID="$HA_URL/"  # Use actual HA URL for client_id (per docs/examples)

    # 1. Wait for API readiness (container health != API ready)
    local retries=60  # Wait up to ~2min
    local api_ready=false
    local status
    while [[ $retries -gt 0 ]]; do
        status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$HA_URL/api/onboarding")
        if [[ "$status" == "200" ]]; then
            api_ready=true
            break
        fi
        sleep 2
        ((retries--))
    done

    if [ "$api_ready" = false ]; then
        log_warn "Home Assistant onboarding API did not become ready after 2min. Account creation skipped."
        return 1
    fi

    # 2. Check if onboarding is still needed (robust jq parsing)
    local onboarding_status=$(curl -s --max-time 10 "$HA_URL/api/onboarding")
    log_info "Onboarding status response: $onboarding_status"
    local user_done
    user_done=$(echo "$onboarding_status" | jq '.[] | select(.step == "user") | .done // false' 2>/dev/null) || user_done="false"
    if [[ "$user_done" == "true" ]]; then
        log_info "Home Assistant user onboarding already complete. Skipping account creation."
        return 0
    fi

    # 3. Create user account
    log_info "Creating 'admin' user..."
    local output=$(curl -s -w "\n%{http_code}" -X POST --max-time 10 \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"Admin\", \"username\": \"admin\", \"password\": \"$HA_PASSWORD\", \"language\": \"en\", \"client_id\": \"$CLIENT_ID\"}" \
        "$HA_URL/api/onboarding/users")
    local response=$(echo "$output" | head -n -1)
    local http_code=$(echo "$output" | tail -n1)
    
    log_info "User creation raw response: $response (HTTP: $http_code)"

    if [[ $http_code -ne 200 && $http_code -ne 201 ]]; then
        log_warn "User creation failed with HTTP $http_code. Response: $response"
        return 1
    fi

    # Parse auth_code (used in modern HA)
    local auth_code=$(echo "$response" | jq -r '.auth_code // empty')
    if [[ -z "$auth_code" ]]; then
        log_warn "Failed to create HA user. API did not return an auth_code. Raw response: $response"
        return 1
    fi

    # 4. Exchange auth_code for access_token (required for further onboarding)
    local token_output=$(curl -s -w "\n%{http_code}" -X POST --max-time 10 \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=authorization_code&code=$auth_code&client_id=$CLIENT_ID" \
        "$HA_URL/auth/token")
    local token_response=$(echo "$token_output" | head -n -1)
    local token_http_code=$(echo "$token_output" | tail -n1)
    
    if [[ $token_http_code -ne 200 ]]; then
        log_warn "Token exchange failed with HTTP $token_http_code. Response: $token_response"
        return 1
    fi
    
    local access_token=$(echo "$token_response" | jq -r '.access_token // empty')
    if [[ -z "$access_token" ]]; then
        log_warn "Failed to exchange auth_code for access_token. Raw response: $token_response"
        return 1
    fi

    # 5. Complete core_config onboarding step (minimal required post-user)
    local core_output=$(curl -s -w "\n%{http_code}" -X POST --max-time 10 \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        -d "{}" \
        "$HA_URL/api/onboarding/core_config")
    local core_response=$(echo "$core_output" | head -n -1)
    local core_http_code=$(echo "$core_output" | tail -n1)
    
    if [[ $core_http_code -ne 200 ]]; then
        log_warn "Core config failed with HTTP $core_http_code. Response: $core_response"
        return 1
    fi
    
    if [[ -z "$core_response" || "$core_response" != "{}" ]]; then  # Empty {} indicates success
        log_warn "Failed to complete core_config. Raw response: $core_response"
        return 1
    fi

    # 6. Verify overall onboarding (optional hardening: re-check status)
    onboarding_status=$(curl -s --max-time 10 "$HA_URL/api/onboarding")
    log_info "Post-onboarding status response: $onboarding_status"
    user_done=$(echo "$onboarding_status" | jq '.[] | select(.step == "user") | .done // false' 2>/dev/null) || user_done="false"
    local core_done=$(echo "$onboarding_status" | jq '.[] | select(.step == "core_config") | .done // false' 2>/dev/null) || core_done="false"
    if [[ "$user_done" != "true" || "$core_done" != "true" ]]; then
        log_warn "Onboarding verification failed post-creation. User done: $user_done, Core done: $core_done"
        return 1
    fi

    log_info "Home Assistant admin user created and minimal onboarding completed successfully."
    return 0
}

# --- Helper: Setup llama-server (llama.cpp inference engine) ---

# Get the llama-server binary path for the current platform
get_llama_bin_path() {
    echo "/home/admin/llama-server/llama-server"
}

# Generate the systemd service file at runtime from model/platform config
generate_llama_service() {
    local bin_path="$1" model_path="$2" ngl="$3" ctx_size="$4" extra_flags="$5"
    local service_dest="/etc/systemd/system/llama-server.service"

    cat > "$service_dest" <<EOF
[Unit]
Description=llama.cpp inference server
After=network.target

[Service]
Type=simple
User=admin
Group=admin
WorkingDirectory=$(dirname "$bin_path")
Environment="LD_LIBRARY_PATH=$(dirname "$bin_path")"
Environment="GGML_VK_DEVICE=0"
ExecStart=${bin_path} \\
  --model ${model_path} \\
  --ctx-size ${ctx_size} \\
  --parallel 1 \\
  --host 127.0.0.1 \\
  --port 8001 \\
  -ngl ${ngl} ${extra_flags:+\\
  $extra_flags}

Restart=always
RestartSec=10
TimeoutStartSec=600
OOMScoreAdjust=-500
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    chmod 644 "$service_dest"
}

# Install prebuilt llama-server with Vulkan GPU support (both platforms)
install_llama_prebuilt() {
    local force="${1:-false}"
    local LLAMA_INSTALL_DIR="/home/admin/llama-server"
    local LLAMA_BIN="${LLAMA_INSTALL_DIR}/llama-server"

    # Fast-path: binary already present (skip unless force update)
    if [[ "$force" != "true" ]] && [[ -x "$LLAMA_BIN" ]]; then
        log_info "llama-server binary already present at $LLAMA_BIN."
        return 0
    fi

    # Install Vulkan runtime (RADV for AMD, same packages for both archs)
    log_info "Installing Vulkan runtime..."
    wait_for_apt_lock
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq mesa-vulkan-drivers libvulkan1 vulkan-tools 2>/dev/null \
        || log_warn "Vulkan driver install returned non-zero. GPU offload may not work."

    # Map architecture to release asset suffix
    local arch_suffix
    if [[ "$HB_ARCH" == "x86_64" ]]; then
        arch_suffix="x64"
    else
        arch_suffix="arm64"
    fi

    log_info "Fetching latest llama.cpp release..."
    local latest_tag
    latest_tag=$(curl -sLf https://api.github.com/repos/ggml-org/llama.cpp/releases/latest \
        | jq -r '.tag_name') || die "Failed to query llama.cpp releases."

    local asset_url
    asset_url=$(curl -sLf "https://api.github.com/repos/ggml-org/llama.cpp/releases/tags/${latest_tag}" \
        | jq -r --arg suffix "$arch_suffix" \
          '.assets[] | select(.name | test("ubuntu.*vulkan.*" + $suffix)) | .browser_download_url' \
        | head -1)

    if [[ -z "$asset_url" || "$asset_url" == "null" ]]; then
        die "No prebuilt Vulkan binary found for ${latest_tag} (${arch_suffix}). Check https://github.com/ggml-org/llama.cpp/releases"
    fi

    log_info "Downloading prebuilt llama-server ${latest_tag} (Vulkan ${arch_suffix})..."
    mkdir -p "$LLAMA_INSTALL_DIR"
    local tmp_archive="/tmp/llama-release.tar.gz"
    wget -O "$tmp_archive" "$asset_url" \
        || die "Failed to download llama-server release."
    tar -xzf "$tmp_archive" -C "$LLAMA_INSTALL_DIR" --strip-components=1
    rm -f "$tmp_archive"

    [[ -x "$LLAMA_BIN" ]] || chmod +x "$LLAMA_BIN"
    [[ -x "$LLAMA_BIN" ]] || die "llama-server binary not found after extraction at $LLAMA_BIN"
    log_info "Installed prebuilt llama-server: $LLAMA_BIN"
}

# Download model file with resume support
download_model() {
    local MODEL_NAME="$1" MODEL_URL="$2" MODEL_PATH="$3" MIN_SIZE="$4"

    log_info "Downloading model: ${MODEL_NAME}..."

    # Pre-flight disk space check
    local avail_kb
    avail_kb=$(df --output=avail /home | tail -1 | tr -d ' ')
    local need_kb=$(( MIN_SIZE / 1024 + 5000000 ))  # model size + 5 GB headroom
    if [[ "$avail_kb" -lt "$need_kb" ]]; then
        die "Insufficient disk space: $(( avail_kb / 1048576 )) GB available, need at least $(( need_kb / 1048576 )) GB."
    fi

    if [[ -f "$MODEL_PATH" ]]; then
        local size
        size=$(stat --format=%s "$MODEL_PATH" 2>/dev/null || echo 0)
        if [[ "$size" -gt "$MIN_SIZE" ]]; then
            log_info "Model already downloaded ($(( size / 1073741824 )) GB). Skipping."
            return 0
        else
            log_warn "Model file exists but appears truncated (${size} bytes). Re-downloading..."
            rm -f "$MODEL_PATH"
        fi
    fi

    log_info "Downloading $(( MIN_SIZE / 1073741824 )) GB+ model. This will take a while..."
    sudo -u admin wget --continue --progress=dot:giga \
        -O "$MODEL_PATH" "$MODEL_URL" \
        || die "Model download failed. Re-run to resume (wget supports resume)."

    local size
    size=$(stat --format=%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [[ "$size" -lt "$MIN_SIZE" ]]; then
        die "Downloaded model is too small (${size} bytes). File may be truncated or URL may be wrong."
    fi
    log_info "Model downloaded: $(( size / 1073741824 )) GB"
}

# Main setup orchestrator
setup_llama_server() {
    log_info "=== Setting up llama-server (${HB_PLATFORM}) ==="
    load_env

    # Read model config from .env (set by dashboard model selector)
    local MODEL_NAME="${AI_MODEL_FILENAME:-}"
    local MODEL_URL="${AI_MODEL_URL:-}"
    local MODEL_PATH="/home/admin/${MODEL_NAME}"
    local NGL="${AI_NGL:-0}"
    local CTX_SIZE="${AI_CTX_SIZE:-8192}"
    local EXTRA_FLAGS="${AI_EXTRA_FLAGS:-}"
    local MIN_SIZE="${AI_MODEL_MIN_SIZE:-1000000000}"
    local LLAMA_BIN
    LLAMA_BIN=$(get_llama_bin_path)
    local HEALTH_URL="http://127.0.0.1:8001/health"

    if [[ -z "$MODEL_NAME" || -z "$MODEL_URL" ]]; then
        die "No AI model configured. Please select a model in the dashboard before installing."
    fi

    # --- [1/5] Fast-path: binary and model already present ---
    log_info "[1/5] Checking for existing llama-server installation..."
    if [[ -x "$LLAMA_BIN" ]] && [[ -f "$MODEL_PATH" ]]; then
        log_info "llama-server and model already present. Syncing service and starting..."
        generate_llama_service "$LLAMA_BIN" "$MODEL_PATH" "$NGL" "$CTX_SIZE" "$EXTRA_FLAGS"
        systemctl daemon-reload
        systemctl enable llama-server
        systemctl restart llama-server
        wait_for_llama_health "$HEALTH_URL" 600
        return $?
    fi

    # --- [2/5] & [3/5] Install binary (platform-specific) ---
    if ! check_internet; then
        die "No internet connection. Cannot install llama-server."
    fi

    log_info "[2/5] Installing prebuilt llama-server (Vulkan)..."
    install_llama_prebuilt

    LLAMA_BIN=$(get_llama_bin_path)
    [[ -x "$LLAMA_BIN" ]] || die "llama-server binary not found at $LLAMA_BIN"
    log_info "[3/5] Binary ready: $LLAMA_BIN"

    # --- [4/5] Download model ---
    log_info "[4/5] Downloading model..."
    download_model "$MODEL_NAME" "$MODEL_URL" "$MODEL_PATH" "$MIN_SIZE"

    # --- [5/5] Deploy service and start ---
    log_info "[5/5] Deploying llama-server service..."
    generate_llama_service "$LLAMA_BIN" "$MODEL_PATH" "$NGL" "$CTX_SIZE" "$EXTRA_FLAGS"
    systemctl daemon-reload
    systemctl enable --now llama-server

    wait_for_llama_health "$HEALTH_URL" 600
    return $?
}

# Helper: poll llama-server health endpoint
wait_for_llama_health() {
    local url="$1"
    local timeout="$2"
    local elapsed=0

    log_info "Waiting for llama-server to load model (up to ${timeout}s)..."
    while [[ $elapsed -lt $timeout ]]; do
        if curl -sf --max-time 3 "$url" >/dev/null 2>&1; then
            log_info "llama-server is healthy on port 8001."
            return 0
        fi
        sleep 10
        elapsed=$((elapsed + 10))
        if (( elapsed % 60 == 0 )); then
            log_info "Still loading model... (${elapsed}s/${timeout}s)"
        fi
    done

    log_error "llama-server did not pass health check within ${timeout}s."
    log_error "Check: journalctl -u llama-server -n 50"
    return 1
}

# --- Helper: Setup whisper-server (speech-to-text) ---

install_whisper_server() {
    local force="${1:-false}"
    local WHISPER_INSTALL_DIR="/home/admin/whisper-server"
    local WHISPER_BIN="${WHISPER_INSTALL_DIR}/whisper-server"

    if [[ "$force" != "true" ]] && [[ -x "$WHISPER_BIN" ]]; then
        log_info "whisper-server binary already present at $WHISPER_BIN."
        return 0
    fi

    # whisper.cpp has no prebuilt Linux binaries — build from source
    log_info "Installing build dependencies for whisper.cpp..."
    wait_for_apt_lock
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq cmake g++ git ffmpeg \
        mesa-vulkan-drivers libvulkan1 vulkan-tools glslc 2>/dev/null \
        || log_warn "Some dependency installs returned non-zero."

    local src_dir="/tmp/whisper.cpp"
    if [[ -d "$src_dir/.git" ]]; then
        log_info "Updating existing whisper.cpp source..."
        git -C "$src_dir" pull --ff-only 2>/dev/null || true
    else
        log_info "Cloning whisper.cpp..."
        rm -rf "$src_dir"
        git clone --depth 1 https://github.com/ggml-org/whisper.cpp.git "$src_dir" \
            || die "Failed to clone whisper.cpp"
    fi

    log_info "Building whisper-server with Vulkan GPU support..."
    cd "$src_dir"
    rm -rf build
    cmake -B build \
        -DGGML_VULKAN=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        || die "CMake configure failed"
    cmake --build build --target whisper-server -j"$(nproc)" \
        || die "whisper-server build failed"

    mkdir -p "$WHISPER_INSTALL_DIR"
    cp build/bin/whisper-server "$WHISPER_BIN"
    chmod +x "$WHISPER_BIN"
    [[ -x "$WHISPER_BIN" ]] || die "whisper-server binary not found after build"
    log_info "Installed whisper-server: $WHISPER_BIN"
}

generate_whisper_services() {
    local bin_path="$1" model_path="$2"
    local internal_port=8003   # whisper-server listens here (WAV only)
    local proxy_port=8002      # proxy listens here (any format → WAV)

    # --- whisper-server (internal, WAV-only) ---
    cat > /etc/systemd/system/whisper-server.service <<EOF
[Unit]
Description=whisper.cpp speech-to-text server
After=network.target

[Service]
Type=simple
User=admin
Group=admin
WorkingDirectory=$(dirname "$bin_path")
Environment="LD_LIBRARY_PATH=$(dirname "$bin_path")"
Environment="GGML_VK_DEVICE=0"
ExecStart=${bin_path} \\
  --model ${model_path} \\
  --host 127.0.0.1 \\
  --port ${internal_port} \\
  --inference-path /v1/audio/transcriptions

Restart=always
RestartSec=10
TimeoutStartSec=120
OOMScoreAdjust=-300
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    chmod 644 /etc/systemd/system/whisper-server.service

    # --- whisper-proxy (converts OGG/Opus → WAV for whisper-server) ---
    # WhatsApp sends voice messages as OGG/Opus; whisper.cpp only accepts WAV.
    # The proxy converts via ffmpeg before forwarding to whisper-server.
    local proxy_script="/home/admin/whisper-server/whisper_proxy.py"
    cp "${SCRIPT_DIR}/whisper_proxy.py" "$proxy_script"
    chown admin:admin "$proxy_script"

    cat > /etc/systemd/system/whisper-proxy.service <<EOF
[Unit]
Description=Whisper audio format proxy (OGG->WAV)
After=whisper-server.service
Requires=whisper-server.service

[Service]
Type=simple
User=admin
Group=admin
Environment="WHISPER_UPSTREAM=http://127.0.0.1:${internal_port}"
Environment="WHISPER_PROXY_PORT=${proxy_port}"
ExecStart=/usr/bin/python3 ${proxy_script}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    chmod 644 /etc/systemd/system/whisper-proxy.service
}

setup_whisper_server() {
    log_info "=== Setting up whisper-server (speech-to-text) ==="
    load_env

    # x86-only feature
    if [[ "$HB_PLATFORM" != "x86_ubuntu" ]]; then
        log_info "Whisper STT is only available on x86 HomeBrain. Skipping."
        return 0
    fi

    # Read whisper model config from .env (or defaults from platform_models.json)
    local MODEL_NAME="${AI_WHISPER_MODEL_FILENAME:-}"
    local MODEL_URL="${AI_WHISPER_MODEL_URL:-}"
    local MIN_SIZE="${AI_WHISPER_MODEL_MIN_SIZE:-600000000}"
    local WHISPER_BIN="/home/admin/whisper-server/whisper-server"

    # If no whisper model configured yet, pick the default from platform_models.json
    if [[ -z "$MODEL_NAME" || -z "$MODEL_URL" ]]; then
        local pm_file="${SCRIPT_DIR}/../config/platform_models.json"
        if [[ -f "$pm_file" ]] && command -v jq >/dev/null 2>&1; then
            MODEL_NAME=$(jq -r '.x86_ubuntu.whisper.models[] | select(.default==true) | .filename' "$pm_file")
            MODEL_URL=$(jq -r '.x86_ubuntu.whisper.models[] | select(.default==true) | .url' "$pm_file")
            MIN_SIZE=$(jq -r '.x86_ubuntu.whisper.models[] | select(.default==true) | .min_size_bytes' "$pm_file")
            local MODEL_ID
            MODEL_ID=$(jq -r '.x86_ubuntu.whisper.models[] | select(.default==true) | .id' "$pm_file")

            # Persist defaults to .env for future fast-path
            update_env_var "AI_WHISPER_MODEL_ID" "$MODEL_ID"
            update_env_var "AI_WHISPER_MODEL_FILENAME" "$MODEL_NAME"
            update_env_var "AI_WHISPER_MODEL_URL" "$MODEL_URL"
            update_env_var "AI_WHISPER_MODEL_MIN_SIZE" "$MIN_SIZE"
        else
            log_warn "No whisper model configured and cannot read defaults. Skipping."
            return 0
        fi
    fi

    local MODEL_PATH="/home/admin/${MODEL_NAME}"

    # --- [1/5] Fast-path: binary and model already present ---
    log_info "[1/5] Checking for existing whisper-server installation..."
    if [[ -x "$WHISPER_BIN" ]] && [[ -f "$MODEL_PATH" ]]; then
        log_info "whisper-server and model already present. Syncing services and starting..."
        generate_whisper_services "$WHISPER_BIN" "$MODEL_PATH"
        systemctl daemon-reload
        systemctl enable whisper-server whisper-proxy
        systemctl restart whisper-server
        systemctl restart whisper-proxy
        wait_for_whisper_health 8002 120
        return $?
    fi

    if ! check_internet; then
        die "No internet connection. Cannot install whisper-server."
    fi

    # --- [2/5] Install ffmpeg (needed by proxy for OGG→WAV conversion) ---
    log_info "[2/5] Installing ffmpeg..."
    wait_for_apt_lock
    export DEBIAN_FRONTEND=noninteractive
    apt-get install -y -qq ffmpeg 2>/dev/null || log_warn "ffmpeg install returned non-zero."

    # --- [3/5] Build whisper-server from source ---
    log_info "[3/5] Building whisper-server (Vulkan)..."
    install_whisper_server

    # --- [4/5] Download model ---
    log_info "[4/5] Downloading whisper model..."
    download_model "$MODEL_NAME" "$MODEL_URL" "$MODEL_PATH" "$MIN_SIZE"

    # --- [5/5] Deploy services and start ---
    log_info "[5/5] Deploying whisper-server + proxy services..."
    generate_whisper_services "$WHISPER_BIN" "$MODEL_PATH"
    systemctl daemon-reload
    systemctl enable --now whisper-server
    systemctl enable --now whisper-proxy

    wait_for_whisper_health 8002 120
    return $?
}

wait_for_whisper_health() {
    local port="$1"
    local timeout="$2"
    local elapsed=0

    log_info "Waiting for whisper-server to become ready (up to ${timeout}s)..."
    while [[ $elapsed -lt $timeout ]]; do
        if curl -sf --max-time 3 "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
            log_info "whisper-server is healthy on port ${port}."
            return 0
        fi
        sleep 5
        elapsed=$((elapsed + 5))
    done

    log_error "whisper-server did not pass health check within ${timeout}s."
    log_error "Check: journalctl -u whisper-server -n 50"
    return 1
}

# --- Helper: Setup OpenClaw AI Agent (system service) ---

# Patch openclaw.json model references to match the selected AI model
patch_openclaw_config() {
    local config_file="$1"
    local model_id="$2"
    local ctx_size="${3:-}"

    if [[ -z "$model_id" ]]; then
        log_warn "No AI_MODEL_ID set. Leaving openclaw.json model config as-is."
        return 0
    fi

    if ! command -v jq >/dev/null 2>&1; then
        log_warn "jq not found. Cannot patch openclaw config model references."
        return 0
    fi

    # Build allowed origins for cross-origin WebSocket from HomeBrain dashboard
    local lan_ip
    lan_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    local origins="[\"http://${lan_ip}\", \"http://${lan_ip}:80\", \"http://localhost\", \"http://127.0.0.1\"]"

    jq --arg id "$model_id" --argjson ctx "${ctx_size:-128000}" --argjson origins "$origins" '
        .models.providers.llamacpp.models[0].id = $id |
        .models.providers.llamacpp.models[0].name = $id |
        .models.providers.llamacpp.models[0].contextWindow = $ctx |
        .agents.defaults.llm.idleTimeoutSeconds = 0 |
        .agents.defaults.model.primary = ("llamacpp/" + $id) |
        .agents.defaults.models = {("llamacpp/" + $id): {}} |
        .browser.executablePath = "/usr/bin/google-chrome-stable" |
        .browser.noSandbox = true |
        .channels.whatsapp.enabled = true |
        .plugins.entries.whatsapp.enabled = true |
        .gateway.controlUi.allowedOrigins = $origins |
        .tools.media.audio.enabled = true |
        .tools.media.audio.scope.default = "allow" |
        .tools.media.audio.models = [{"provider": "openai", "model": "whisper-1", "capabilities": ["audio"], "baseUrl": "http://127.0.0.1:8002/v1", "timeoutSeconds": 30}] |
        .models.providers.openai = {"apiKey": "dummy-local-whisper", "baseUrl": "http://127.0.0.1:8002/v1", "models": []}
    ' "$config_file" > "${config_file}.tmp" && mv "${config_file}.tmp" "$config_file"
    log_info "Patched openclaw.json with model: $model_id (ctx: ${ctx_size:-128000})"
}

# Run a command as admin with systemd user session environment
# Required for openclaw daemon/gateway which uses systemd user services
run_as_admin() {
    local admin_uid
    admin_uid=$(id -u admin)
    # Ensure linger is enabled (allows user services without login)
    loginctl enable-linger admin 2>/dev/null || true
    # Ensure runtime dir exists
    mkdir -p "/run/user/${admin_uid}" 2>/dev/null || true
    chown admin:admin "/run/user/${admin_uid}" 2>/dev/null || true
    sudo -u admin \
        XDG_RUNTIME_DIR="/run/user/${admin_uid}" \
        DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${admin_uid}/bus" \
        "$@"
}

setup_openclaw() {
    log_info "=== Setting up OpenClaw AI Assistant ==="
    load_env

    # Pre-flight: warn if llama-server is not reachable
    if ! curl -sf --max-time 5 http://127.0.0.1:8001/health >/dev/null 2>&1; then
        log_warn "llama-server is not responding on port 8001. OpenClaw may not work correctly."
    fi

    local config_src="${SCRIPT_DIR}/../config/openclaw.json"
    local config_dest="/home/admin/.openclaw/openclaw.json"
    local model_id="${AI_MODEL_ID:-}"

    # --- Step 1: Fast-path if binary already installed ---
    log_info "[1/3] Checking for existing OpenClaw installation..."
    if command -v openclaw >/dev/null 2>&1; then
        log_info "OpenClaw already installed ($(openclaw --version 2>/dev/null || echo 'unknown version')). Syncing config and starting..."
        mkdir -p /home/admin/.openclaw
        cp "$config_src" "$config_dest"
        patch_openclaw_config "$config_dest" "$model_id" "${AI_CTX_SIZE:-}"
        chown -R admin:admin /home/admin/.openclaw
        chmod 600 "$config_dest"
        run_as_admin openclaw daemon install 2>/dev/null || true
        run_as_admin openclaw daemon start \
            || { log_error "daemon start failed. Try: sudo -u admin openclaw daemon install"; return 1; }
        log_info "=== OpenClaw started (fast path) ==="
        return 0
    fi

    # --- Step 2: Fresh install ---
    log_info "[2/3] Installing OpenClaw..."

    if ! check_internet; then
        die "No internet connection. Cannot install OpenClaw."
    fi

    # OpenClaw requires Node.js 22.14+ (24 recommended)
    local need_node=false
    if ! command -v node >/dev/null 2>&1; then
        need_node=true
    else
        local node_major
        node_major=$(node --version 2>/dev/null | sed 's/v\([0-9]*\).*/\1/')
        if [[ "$node_major" -lt 22 ]]; then
            log_info "Node.js ${node_major} found but 22+ is required. Upgrading..."
            need_node=true
        fi
    fi

    if [[ "$need_node" == "true" ]]; then
        log_info "Installing Node.js 22 LTS via NodeSource..."
        wait_for_apt_lock
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        apt-get install -y -qq nodejs
    fi

    log_info "Node $(node --version)"
    # --no-onboard: skip interactive wizard — we manage config ourselves
    log_info "Downloading and installing OpenClaw (this may take a minute)..."
    curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard \
        || die "OpenClaw install failed. See https://docs.openclaw.ai for help."

    command -v openclaw >/dev/null 2>&1 \
        || die "openclaw binary not found in PATH after install. Check the install output above."

    log_info "Installed: $(openclaw --version 2>/dev/null || echo 'ok')"

    # --- Step 3: Write config and register daemon ---
    log_info "[3/3] Writing config and registering daemon..."
    if [[ ! -f "$config_src" ]]; then
        die "config/openclaw.json not found at $config_src — ensure it is committed to the repository."
    fi
    mkdir -p /home/admin/.openclaw
    cp "$config_src" "$config_dest"
    patch_openclaw_config "$config_dest" "$model_id" "${AI_CTX_SIZE:-}"
    chown -R admin:admin /home/admin/.openclaw
    chmod 600 "$config_dest"
    log_info "Config written to $config_dest"

    # Let openclaw install its own systemd service (runs as admin user)
    run_as_admin openclaw daemon install \
        || die "openclaw daemon install failed."
    run_as_admin openclaw daemon start \
        || die "openclaw daemon start failed."

    # Verify startup (up to 30 s)
    local retries=0
    while [[ $retries -lt 15 ]]; do
        if run_as_admin openclaw gateway status 2>/dev/null | grep -qi "running\|active\|online"; then
            local ip
            ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
            log_info "OpenClaw is running. Access at http://${ip}:18789"
            log_info "=== OpenClaw setup complete ==="
            return 0
        fi
        sleep 2
        ((retries++))
    done

    log_error "OpenClaw did not report as running within 30 s."
    log_error "Check status with: sudo -u admin openclaw gateway status"
    return 1
}

# --- Main Dispatch ---
case "${1:-}" in
    system_status)
        get_system_config_status
        ;;
    watchdog)
        configure_watchdog "${2}"
        ;;
    cron)
        configure_nc_cron
        ;;
    pci)
        configure_pci_speed "${2}"
        ;;
    redis_status)
        nc_cid=$(get_nc_cid)
        # Robustness: Check if container exists AND is actually running
        if [[ -z "$nc_cid" ]] || [[ $(docker inspect -f '{{.State.Running}}' "$nc_cid" 2>/dev/null) != "true" ]]; then
             echo "disconnected"
             exit 0
        fi

        # Check if the 'host' value in Nextcloud config is set to 'redis'
        host_val=$(docker exec --user www-data "$nc_cid" php occ config:system:get redis host 2>/dev/null || echo "")
        
        if [[ "$host_val" == "redis" ]]; then
            echo "connected"
        else
            echo "unconfigured"
        fi
        ;;
    redis_configure)
        configure_nextcloud_redis
        ;;
    setup)
        setup_ftp_user "${2}" "${3}" "${4}"
        ;;
    delete)
        delete_ftp_user "${2}"
        ;;
    activate_tunnels)
        activate_tunnels
        ;;
    ha_admin)
        create_ha_admin "${2:-}"
        ;;
    setup_ai)
        setup_llama_server || { log_error "llama-server setup failed. Aborting AI stack install."; exit 1; }
        setup_whisper_server || log_warn "whisper-server setup failed. Voice messages will not be transcribed."
        setup_openclaw
        ;;
    stop_ai)
        run_as_admin openclaw daemon stop 2>/dev/null || true
        log_info "OpenClaw stopped."
        systemctl disable --now llama-server 2>/dev/null || true
        log_info "llama-server stopped and disabled."
        systemctl disable --now whisper-proxy 2>/dev/null || true
        systemctl disable --now whisper-server 2>/dev/null || true
        log_info "whisper-server and proxy stopped and disabled."
        ;;
    switch_model)
        log_info "=== Switching AI model ==="
        # Stop running services
        run_as_admin openclaw daemon stop 2>/dev/null || true
        systemctl stop llama-server 2>/dev/null || true
        systemctl stop whisper-server 2>/dev/null || true
        log_info "Stopped AI services."

        # Re-run full setup (downloads new model if needed, regenerates service, starts)
        # Previously-downloaded models are kept on disk for faster switching.
        setup_llama_server || { log_error "Model switch failed during llama-server setup."; exit 1; }
        setup_whisper_server || log_warn "whisper-server restart failed."
        setup_openclaw

        log_info "Model switch complete."
        ;;
    update_llama)
        log_info "=== Updating llama-server to latest release ==="
        load_env
        systemctl stop llama-server 2>/dev/null || true
        install_llama_prebuilt "true"
        setup_llama_server || { log_error "Failed to restart after update."; exit 1; }
        log_info "llama-server updated and restarted."
        ;;
    *)
        echo "Usage: $0 {setup <nc_user> <ftp_user> <ftp_pass> | delete <ftp_user>}"
        exit 1
        ;;
esac